version: "3.9"

services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/work/data
